const categories = [
    "Electronics",
    "Clothing & Fashion",
    "Home & Kitchen",
    "Beauty & Personal Care",
    "Health & Wellness",
    "Sports & Outdoors",
    "Toys & Games",
    "Books & Stationery",
    "Automotive",
    "Groceries",
    "Baby & Kids",
    "Jewelry & Accessories",
    "Footwear",
    "Mobile Phones & Accessories",
    "Computers & Laptops",
    "Furniture & Decor",
    "Appliances",
    "Musical Instruments",
    "Art & Craft Supplies",
    "Pet Supplies",
    "Office Supplies",
    "Garden & Outdoor Living",
    "Travel & Luggage",
    "Watches",
    "Gaming",
    "Cameras & Photography",
    "Industrial Supplies",
    "Gifts & Seasonal Items",
    "Tools & Hardware",
    "Food & Beverages",
    "DIY & Hobbies"
];

export default categories